[package]
name = "extract_sitelinks_qlever"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = { version = "0.31", features = ["bundled"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ureq = { version = "2.9", features = ["json"] }
indicatif = "0.17"
rayon = "1.10"
crossbeam-channel = "0.5"

[profile.release]
opt-level = 3
lto = true
